name: 'Prepare pnpm installation'
description: 'Ensures pnpm is installed and ready to use in the workflow environment.'
inputs:
  version:
    description: 'The version of pnpm to install. If not specified, the latest version will be installed.'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Node.js and pnpm (${{ inputs.version }})
      if: ${{ inputs.version }}
      uses: pnpm/setup@v2
      with:
        version: ${{ inputs.version }}
        install: false

    - name: Install Node.js and pnpm
      if: ${{ !inputs.version }}
      uses: pnpm/setup@v2
      with:
        install: false

    - name: Install dependencies
      shell: bash
      run: pnpm ci
