name: Testing, Validation
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Prepare Node.js and pnpm
      uses: ./.github/actions/pnpm-prepare

    - name: Run typechecking
      run: pnpm tsc

    - name: Run tests
      run: pnpm test
